#!/usr/bin/env bash
#nmcli c import type openvpn file ./vpn_ensimag.ovpn
#nmcli c modify vpn_ensimag ipv4.never-default true
#nmcli c modify vpn_ensimag vpn.user-name bartolor
nmcli c up vpn_ensimag --ask
